bind = ["127.0.0.1", 8080]
timeout = 10

[[hook]]
location = "/hello"
program = "echo"
args = [
    "hello",
]
secret = "abcdefg"

[[hook]]
location = "/cat"
# Stdin reads from POST body.
program = "cat"
